#!/bin/bash
# Installation
REINSTALL=false
WORKFLOW_DIR="$HOME/africapolis-workflow"
usage() {
    echo "Usage: $0 [--preset <PRESET_FILE>] <INPUT_FILE>"
    echo "       $0 --update"
    echo "  <INPUT_FILE>  Vector file (.gpkg) or shapefile (.shp) holding the settlement polygons"
    echo "  --preset      CWL job file holding the parameters of the run, including the partition"
    echo "                depth. Defaults to $WORKFLOW_DIR/jobs/default.yml,"
    echo "                see $WORKFLOW_DIR/jobs for the available presets"
    echo "  --update      Reinstall the workflow and exit"
}

while [[ $# -gt 0 ]]; do
    case $1 in
        --update)
            REINSTALL=true
            shift
            ;;
        *)
            break
            ;;
    esac
done

if [ ! -d "$WORKFLOW_DIR" ] || [ "$REINSTALL" = true ]; then
    rm -rf "$WORKFLOW_DIR"
    mkdir -p "$WORKFLOW_DIR"
    cd $TMPDIR
    rm -rf africapolis
    git clone https://github.com/LoloGruber/africapolis.git
    cp africapolis/Africapolis.cwl $WORKFLOW_DIR/Africapolis.cwl
    cp -r africapolis/cwl $WORKFLOW_DIR/cwl
    cp -r africapolis/jobs $WORKFLOW_DIR/jobs
    cp -r africapolis/data/input $WORKFLOW_DIR/input
    cd $WORKFLOW_DIR
    module load python 
    python -m venv venv
    source venv/bin/activate
    pip install toil[cwl]
    pip install nodeenv
    nodeenv -p
    echo "Installation complete. You can now run the workflow using the following command:"
    usage
    exit 0
fi
# Load modules
module load apptainer
module load gcc # required by nodejs
module load squashfs
source $WORKFLOW_DIR/venv/bin/activate
# Parse command line arguments
INPUT_FILE=""
PRESET_FILE="$WORKFLOW_DIR/jobs/default.yml"
while [[ $# -gt 0 ]]; do
    case $1 in
        --preset)
            PRESET_FILE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            echo "Error: Unknown option $1"
            usage
            exit 1
            ;;
        *)
            if [ -n "$INPUT_FILE" ]; then
                echo "Error: More than one input file given"
                usage
                exit 1
            fi
            INPUT_FILE="$1"
            shift
            ;;
    esac
done
# Validate input parameters
if [ -z "$INPUT_FILE" ]; then
    echo "Error: Missing input file."
    usage
    exit 1
fi
if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: Input file '$INPUT_FILE' does not exist."
    exit 1
fi
if [ ! -f "$PRESET_FILE" ]; then
    echo "Error: Preset file '$PRESET_FILE' does not exist."
    exit 1
fi
# Convert to absolute paths
INPUT_FILE="$(cd "$(dirname "$INPUT_FILE")" && pwd)/$(basename "$INPUT_FILE")"
PRESET_FILE="$(cd "$(dirname "$PRESET_FILE")" && pwd)/$(basename "$PRESET_FILE")"
EXPERIMENT_NAME="$(basename "${INPUT_FILE%.*}")_$(basename "$PRESET_FILE" .yml)"
WORKFLOW_FILE="$WORKFLOW_DIR/Africapolis.cwl"
# Setup JobStore directory
JOB_STORE="$TMPDIR/toil"
mkdir -p "$JOB_STORE"
rm -rf "$JOB_STORE"
# Create output directory based on input file name and preset file name
OUTPUT_DIR="$WORKFLOW_DIR/output/$EXPERIMENT_NAME"
mkdir -p "$OUTPUT_DIR"
cd "$OUTPUT_DIR"
# A cwl job file describes a run completely and cannot be combined with command line arguments, so
# the parameters of the preset and the input of this run are merged into a job file first. Every
# parameter but the input file is taken from the preset, the partition depth among them.
if [[ "$INPUT_FILE" == *.shp ]]; then INPUT_KEY="shapefile"; else INPUT_KEY="vectorFile"; fi
JOB_FILE="$OUTPUT_DIR/job.yml"
{
    echo "# Generated by run-africapolis.sh from $PRESET_FILE"
    echo "$INPUT_KEY:"
    echo "  class: File"
    echo "  path: $INPUT_FILE"
    # Take the parameters of the preset, dropping the input it ships with
    awk '/^[^[:space:]#]/ { skip = ($0 ~ /^(vectorFile|shapefile):/) } !skip' "$PRESET_FILE"
} > "$JOB_FILE"
echo "Running workflow with the following parameters:"
cat "$JOB_FILE"
# Run TOIL CWL workflow
SLURM_TIME=23:59:59
toil-cwl-runner --singularity --batchSystem slurm --jobStore $JOB_STORE --doubleMem True --retryCount 2 --slurmTime $SLURM_TIME --writeLogs $WORKFLOW_DIR/log $WORKFLOW_FILE "$JOB_FILE"
if [ $? -eq 0 ]; then
    echo "Workflow execution complete. Output files are located in $OUTPUT_DIR"
fi
